### ISSUE TITLE
Searching in Tischendorf starts with Genesis 1

### ISSUE THREAD

**Issue by michaelstalker** [digitalbiblesociety/browserbible#20]
When I search for a string and I'm using Tischendorf, the text search begins with Genesis 1 and crawls through the entire Old Testament. I don't think Teschendorf has an Old Testament, so I'm not sure what data source the app is searching. At the very least, it would be a nice optimization to begin searching in Matthew 1 for Bibles that only contain a New Testament.

**Comment by johndyer** [comment]
Good point! We're doing that in browserbible-3.

See http://biblewebapp.com/v3

JD

On Wed, Nov 13, 2013 at 7:38 PM, Michael Stalker
notifications@github.comwrote:

> When I search for a string and I'm using Tischendorf, the text search
> begins with Genesis 1 and crawls through the entire Old Testament. I don't
> think Teschendorf has an Old Testament, so I'm not sure what data source
> the app is searching. At the very least, it would be a nice optimization to
> begin searching in Matthew 1 for Bibles that only contain a New Testament.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/digitalbiblesociety/browserbible/issues/20
> .

## 

John Dyer - http://j.hn/

**Comment by michaelstalker** [comment]
Cool! Are you allowing others to contribute to this project? If so, I might like to work on it some.

**Comment by johndyer** [comment]
Of course! We'd love more contributors. I've had a few people send things
via email, but using git is better.

Let's move it over to the
https://github.com/digitalbiblesociety/browserbible-3 project and let me
know what you're thinking.

JD

On Fri, Nov 15, 2013 at 9:14 AM, Michael Stalker
notifications@github.comwrote:

> Cool! Are you allowing others to contribute to this project? If so, I
> might like to work on it some.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/digitalbiblesociety/browserbible/issues/20#issuecomment-28575730
> .

## 

John Dyer - http://j.hn/

**Comment by michaelstalker** [comment]
It looks like it's been a few months since any commits have been made on the current version of the app. Are you doing any more active work on this repo, or are you doing all new work and fixes at https://github.com/digitalbiblesociety/browserbible-3?

**Comment by KenBitgood** [comment]
Hey Michael,
I just wanted to thank you for your interest in helping us with inScript.
We would value your input, your code and your imagination in making this a
better tool for the closed access world to use.
inScript is in its third revision now and is looking ready for prime time in
the first quarter of 2014.
Would you like to be one of our few beta testers?

Ken Bitgood
CEO, Digital Bible Society
God's Word accessible in every language
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
936-273-3131 office  • 936-309-0063 fax
POBox 7445 • The Woodlands, Texas, 77387
Ken@dbsBible.org 
applewebdata://EA201B43-A70F-4A74-8312-D395DFC7AD25/ken@dbsBible.org  •
www.DigitalBibleSociety.org
<applewebdata://EA201B43-A70F-4A74-8312-D395DFC7AD25/www.DigitalBibleSociety
.org> 

From:  Michael Stalker notifications@github.com
Reply-To:  digitalbiblesociety/browserbible
<reply+i-22637047-8f060d8e5ef6fd0d93952fa0ccbdc121a55527ce-1375154@reply.git
hub.com>
Date:  Saturday, November 16, 2013 at 10:58 AM
To:  digitalbiblesociety/browserbible browserbible@noreply.github.com
Subject:  Re: [browserbible] Searching in Tischendorf starts with Genesis 1
(#20)

It looks like it's been a few months since any commits have been made on the
current version of the app. Are you doing any more active work on this repo,
or are you doing all new work and fixes at
https://github.com/digitalbiblesociety/browserbible-3?

—
Reply to this email directly or view it on GitHub
<https://github.com/digitalbiblesociety/browserbible/issues/20#issuecomment-
28630686> .

**Comment by michaelstalker** [comment]
Hi Ken,

I was looking to help out with the Browser Bible app. I have an M.Div., and
have been looking for an opportunity to use my development skills to work
with biblical languages. I'm thankful for John's willingness to let me
contribute to that app!

Is inScript something that you all have been developing, as well?

-Michael
