### ISSUE TITLE
Running the app 

### ISSUE THREAD

**Issue by BryceSteuer** [digitalbiblesociety/browserbible#23]
What is the standard method to run this app locally? Can I use Visual Studio or nodeJS if so, how? Also I attempted to run it in Chrome by running the given Command Prompt, again to no avail. ps I really appreciate this app, I think it rivals andBible in quality. Keep up the great work

**Comment by JH108** [comment]
From what I remember you'd just "run the app" by loading the index.html file into your web browser but I think most modern browsers will block using the local file so you may have to experiment with it. 

 Also, the newest version of this project is located [here](https://github.com/digitalbiblesociety/browserbible-3) and has instructions for how to build the project. 

Optionally you could use something like [http-server](https://github.com/http-party/http-server) or build your own `node.js` server to serve the HTML file. 

**Excerpt from http-server docs**
## Usage:

     http-server [path] [options]

`[path]` defaults to `./public` if the folder exists, and `./` otherwise.

*Now you can visit http://localhost:8080 to view your server*

**Note:** Caching is on by default. Add `-c-1` as an option to disable caching.

Here is a working example if you have a current version of npm and node.js already setup on your machine: `npx http-server ./browserbible`. There will be other steps required to install the resources but hopefully, this will get you started.

**Comment by BryceSteuer** [comment]
Thank you, I appreciate that.
